version: '3.8'

services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - /var/lib/postgresql/data/
    env_file:
      - ./.env
  web:
    image: ninefiveblade/yamdb_final:v2
    restart: always
    volumes:
      - static_value:/app/api_yamdb/static/
      - media_value:/app/api_yamdb/media/
    depends_on:
      - db
    env_file:
      - ./.env
    command: gunicorn api_yamdb.wsgi:application --bind 0:8000
  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - web

volumes:
  static_value:
  media_value: